version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    command: flask run
    networks:
      - mynet
    volumes:
      - myvol:/home/app
  redis:
    image: "redis:alpine"
    networks:
      - mynet

networks:
  mynet:
volumes:
  myvol: